### ISSUE TITLE
error when trying to use the link to create a session

### ISSUE THREAD

**Issue by Yuri-Tiofilo** [Fitbit/sdk-oauth#7]
Error when using the link to create a session in case this test link: https://www.fitbit.com/oauth2/authorize?response_type=code&client_id=22942C&redirect_uri=https%3A%2F%2Fexample.com%2Ffitbit_auth&scope=activity% 20nutrition% 20heartrate% 20location% 20nutrition% 20profile% 20settings% 20sleep% 20social% 20weight

This error happened when using the library to direct this link, the library is: oauth2-popup-flow version: ^ 1.1.0.

Doing the following process:

a file is created that will be imported in the future to perform the function in this case the file is called: auth.js with the following description:
````
import { OAuth2PopupFlow } from 'oauth2-popup-flow';

export default new OAuth2PopupFlow({
  authorizationUri: 'https://www.fitbit.com/oauth2/authorize?response_type=code&client_id=22942C&redirect_uri=https%3A%2F%2Fexample.com%2Ffitbit_auth&scope=activity%20nutrition%20heartrate%20location%20nutrition%20profile%20settings%20sleep%20social%20weight',
  clientId: '50c71b28db301de7ee0c57fdce9d433f',
  redirectUri: 'http://localhost:8080/redirect',
  scope: 'openid profile',
  responseType: 'id_token',
  accessTokenResponseKey: 'id_token',
  additionalAuthorizationParameters: {
    nonce: Math.random().toString(),
  },
});
````

After that we have to import it into the App.js file that works as follows:

````
import React from 'react';
import auth from './auth';

function App() {
  async function test() {
    await auth.tryLoginPopup();
  }

  return (
    <div>
      <button type="button" onClick={() => {
        test();
      }}>test</button>
    </div>
  );
}

export default App;
````

Result after clicking the button is the image below:

![image](https://user-images.githubusercontent.com/49408968/89425858-d9655700-d70f-11ea-895b-9d1ea8d1a121.png)

After that I could not perform any other step, with this we have this error.

**Comment by orviwan** [comment]
I think you'll need to post this question on the community forum for the Web API. https://community.fitbit.com/t5/Web-API-Development/bd-p/dev

This project is a sample app for the Device SDK.
